8299968: Second call to Stage.setScene() create sizing issue with uiScale > 1.0
openjdk/jfx pull request #1054
Opened 2023-03-07 14:33 UTC by lukostyra

Issue happened during setting a new Scene - updating a new View was done while the Window reference it kept was null. This caused it to default scaling values to 1.0f (or 100%) while processing a resize notification, which for high DPI screens with scaling different than 100% caused UI issues.

Resolved by splitting `_setView()` native call into two parts - first one sets the view, then back in JVM side we set a correct Window reference, then we trigger the notification. It has to be triggered from native side, because Windows backend of Glass sends back new width/height pulled from WinAPI `::GetClientRect()` call.

In process of working on this issue I also found another scenario causing the same problem - calling `Stage.setScene()` after `Stage.show()`. The patch fixed that case as well.

Added a system test which is supposed to check for above issues. I didn't limit it to run only on platforms with UI scaling enabled because it also serves as a good sanity check in case there are some other changes to code that might move/scale the UI unwantingly. I tested this patch both on macOS Ventura and Windows 11, with `d9c091f` all tests pass while without `d9c091f` on Windows tests `testShowAndSetScene` and `testSecondSetScene` fail as expected.

2023-03-07 14:37 UTC, kevinrushforth commented
/reviewers 2

2023-03-07 14:39 UTC, kevinrushforth commented
I'll test and review it. One quick comment: since the newly-added system test uses Robot, the test class will need to move under the `test.robot` hierarchy so it will be correctly excluded unless `-PUSE_ROBOT=true`.

2023-03-08 14:47 UTC, kevinrushforth reviewed
The fix looks good to me, although I want to test on a dual screen setup. I doubt there will be any difference in behavior, since the fix looks independent of the screen. I did leave one minor suggestion on a comment you added.

The test fails for me intermittently, which suggests that there is a timing issue. You will likely need to use a latch to wait for the button to be clicked (or a sleep of around 1/2 sec) rather than immediately testing `wasClicked`.

2023-03-08 14:47 UTC, kevinrushforth commented on modules/javafx.graphics/src/main/java/com/sun/glass/ui/Window.java
> +            // JDK-8299968: View size update (especially notifyResize event) have to happen
Minor: we generally don't put a bug ID in comments in the implementation when fixing a bug.

2023-03-09 14:52 UTC, lukostyra commented
I was wondering if that could be an issue, but on my system it was (of course) fine.

I changed the test to wait for a Latch instead of checking `wasClicked`. If it timeouts after a few seconds it means the test fails. Checked it again and it seems to be stable now.

2023-03-13 11:22 UTC, arapte commented
We have a bug for setting scene after showing stage: [JDK-8199204](https://bugs.openjdk.org/browse/JDK-8199204).
It seems to be fixed by this PR.

/Issue add JDK-8199204

2023-03-13 11:36 UTC, arapte requested changes
The fix seems good to me. Suggesting few changes in test and a minor correction in source.

2023-03-13 11:36 UTC, arapte commented on tests/system/src/test/java/test/robot/javafx/stage/SetSceneScalingTest.java
> +                                        Platform.runLater(shownLatch::countDown));
Can be changed to : 
```
stage.setOnShown(l -> {
    Platform.runLater(() -> startupLatch.countDown());
});
```

2023-03-13 12:37 UTC, lukostyra commented
/issue add JDK-8199204

2023-03-13 12:52 UTC, lukostyra commented on modules/javafx.graphics/src/main/native-glass/win/GlassWindow.cpp
>      GlassView * view;
Indeed a leftover - removed

2023-03-13 13:05 UTC, lukostyra commented on tests/system/src/test/java/test/robot/javafx/stage/SetSceneScalingTest.java
> +            robot.mouseMove(400, 400);
Done

2023-03-13 13:06 UTC, lukostyra commented on tests/system/src/test/java/test/robot/javafx/stage/SetSceneScalingTest.java
> +                                        Platform.runLater(shownLatch::countDown));
Done

2023-03-13 15:42 UTC, kevinrushforth commented
Now that https://bugs.openjdk.org/browse/JDK-8199204 is closed as a duplicate, please `/issue remove JDK-8199204`.

2023-03-13 18:39 UTC, kevinrushforth approved these changes
Looks good.

2023-03-14 13:10 UTC, arapte approved these changes

2023-03-14 13:13 UTC, lukostyra commented
/integrate

2023-03-14 13:28 UTC, kevinrushforth commented
/sponsor

2023-03-14 13:30 UTC, closed without merging