8154038: Spinner's converter should update its editor
openjdk/jfx pull request #1057
Opened 2023-03-10 11:38 UTC by karthikpandelu

When converter was changed, `setText` method of spinner was not invoked to update the spinner text using new converter.

Added a listener to converter property of `SpinnerValueFactory` to call `setText` so that spinner text is updated using new converter.

Added unit test to validate the fix. Along with spinner of Double type, added a spinner of Integer type as well so that the fix is validated using 2 types of spinner.

2023-03-15 12:16 UTC, aghaisas requested changes

2023-03-15 18:10 UTC, andy-goryachev-oracle commented
Added SpinnerPage to the MonkeyTester

https://github.com/andy-goryachev-oracle/Test/blob/main/src/goryachev/monkey/MonkeyTesterApp.java
https://github.com/andy-goryachev-oracle/Test/blob/main/src/goryachev/monkey/pages/SpinnerPage.java

2023-03-16 06:08 UTC, karthikpandelu commented on modules/javafx.controls/src/main/java/javafx/scene/control/Spinner.java
> +                        newFactory.converterProperty().addListener((o, oldValue, newValue) -> {
Updated the code. Please check

2023-03-16 06:09 UTC, karthikpandelu commented on modules/javafx.controls/src/test/java/test/javafx/scene/control/SpinnerTest.java
> +    @Test public void testSpinnerEditorUpdateOnConverterChange() {
Created separate tests for each type of Spinner. Please check

2023-03-20 08:57 UTC, aghaisas approved these changes
Looks good!

2023-03-21 05:28 UTC, karthikpandelu commented
/integrate

2023-03-21 05:55 UTC, aghaisas commented
/sponsor

2023-03-21 05:57 UTC, closed without merging