8306424: [testbug] DatePickerUpdateOnAlertCloseTest fails on MacOS
openjdk/jfx pull request #1104
Opened 2023-04-20 13:28 UTC by karthikpandelu

Test was failing because `CountDownLatch` was not used to make sure that new date is selected and the delay present was not sufficient.
If the current date is on the left edge of the date picker, this test would fail because of the way new date was selected using mouse click.

Added `CountDownLatch` to make sure that alert dialog is closed before asserting the date. Updated the test to select new date using robot `keyType` method instead of mouse click so that the test becomes robust.

Ran the test individually and along with all system tests on Mac. No failure found.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306424](https://bugs.openjdk.org/browse/JDK-8306424): [testbug] DatePickerUpdateOnAlertCloseTest fails on MacOS

### Reviewers
 * [Andy Goryachev](https://openjdk.org/census#angorya) (@andy-goryachev-oracle - Committer)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1104/head:pull/1104` \
`$ git checkout pull/1104`

Update a local copy of the PR: \
`$ git checkout pull/1104` \
`$ git pull https://git.openjdk.org/jfx.git pull/1104/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1104`

View PR using the GUI difftool: \
`$ git pr show -t 1104`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1104.diff">https://git.openjdk.org/jfx/pull/1104.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1104#issuecomment-1516339853)

2023-04-20 13:41 UTC, kevinrushforth commented
The change from using the mouse to using the keyboard might change the nature of the test. Have you verified that it would still catch the original bug for which the test was created?

2023-04-20 18:26 UTC, kevinrushforth commented
@andy-goryachev-oracle Can you take a look at this?

2023-04-20 19:21 UTC, andy-goryachev-oracle commented
I think the change is not equivalent, but it might be a good addition to the existing test.  We may add changing the selected date with the keyboard (RIGHT ARROW key), and also modify the mouse test by clicking first at coordinates (width * 0.3, height * 0.5), saving the selected date1, then clicking at (width * 0.6. height * 0.5) and checking that the new selected date != date1.  This will ensure the mouse-based test always works regardless of current date, and we add another test which I think is also good (right arrow key works always).

Minor comments:
- please update the copyright year
- please update the class javadoc

2023-04-20 19:22 UTC, andy-goryachev-oracle requested changes
I'd recommend bringing back a (slightly modified) mouse test and keeping the keyboard test.
+ minor suggestions.

2023-04-21 05:26 UTC, karthikpandelu commented
> The change from using the mouse to using the keyboard might change the nature of the test. Have you verified that it would still catch the original bug for which the test was created?

Yes it still catches the original bug.

> I'd recommend bringing back a (slightly modified) mouse test and keeping the keyboard test.
> 
>     * minor suggestions.

Sure. I'll keep both tests and modify the mouse test as suggested.

2023-04-24 11:42 UTC, karthikpandelu commented
Added mouse based test back and stabilized it. Addressed  other review comments.
Please review.

2023-04-24 16:58 UTC, andy-goryachev-oracle approved these changes
looks good now, thanks!

2023-04-24 17:41 UTC, kevinrushforth approved these changes

2023-04-24 17:48 UTC, andy-goryachev-oracle commented
/sponsor

2023-04-25 04:12 UTC, karthikpandelu commented
/integrate

2023-04-25 04:17 UTC, karthikpandelu commented
@andy-goryachev-oracle could you please comment again to sponsor? I had not put integrate comment before you had commented to sponsor.

2023-04-25 15:27 UTC, andy-goryachev-oracle commented
/sponsor

2023-04-25 15:28 UTC, closed without merging