8304922: [testbug] SliderTooltipNPETest fails on Linux
openjdk/jfx pull request #1119
Opened 2023-04-28 12:06 UTC by karthikpandelu

The test was failing on the first run and then it was not failing. Cause for the failure looked to be the UI state not getting updated. Hence added call to `Toolkit` `firePulse` method.

Able to run the test consistently without failure in Linux after the fix.

2023-04-28 14:24 UTC, kevinrushforth reviewed
It doesn't work for me.

2023-04-28 15:01 UTC, karthikpandelu commented on tests/system/src/test/java/test/robot/javafx/scene/SliderTooltipNPETest.java
> +            Toolkit.getToolkit().firePulse();
Oh Okay! Let me check on that again.
Looks like the failure is not consistent in all the Linux systems. Even without the fix it was failing only on the first run for me in VM as well as in Ubuntu workstation.

2023-05-11 12:04 UTC, karthikpandelu commented
Since `consumeAutoHidingEvents` property value is asserted in the test, I'm suspecting that it is getting asserted before the mouse moves away from the slider and `consumeAutoHidingEvents` property value is reset to original value.
Since the test is not failing consistently for me in Ubuntu, I believe possibility of product issue is less. Hence  added a latch and small delay to make sure that the property value is asserted only after the mouse is moved.
@kevinrushforth  could you please check this fix.
I have ran the test in Ubuntu 22.04 VM multiple times and test didn't fail.

2023-06-12 05:39 UTC, karthikpandelu commented
@kevinrushforth could you please check the updated fix whenever possible?

2023-06-12 21:35 UTC, kevinrushforth requested changes
It still fails the first time I run it. I ran it on a physical machine, and I now know why. I can make it fail every time by moving the mouse away from the center of the screen (so that it is outside of where the window will appear).

The problem is that the tooltip will not show up on Linux if you directly move the cursor with Robot to be over the control without it ever having been somewhere else in the window first. So the only reason it works on subsequent runs is that the mouse is left in a position such that it will be over the window when the test is run the next time.

In general, it's also a good idea to click in the window to ensure that it is activated. The only other  robot-based test that shows a Tooltip first moves the mouse to the upper-left corner of the scene and then does a mouse click. Adding that code to your patch causes it to work.

So I recommend adding the following to the test (in addition to the changes you already made, which look good).

```
diff --git a/tests/system/src/test/java/test/robot/javafx/scene/SliderTooltipNPETest.java b/tests/system/src/test/java/test/robot/javafx/scene/SliderTooltipNPETest.java
--- a/tests/system/src/test/java/test/robot/javafx/scene/SliderTooltipNPETest.java
+++ b/tests/system/src/test/java/test/robot/javafx/scene/SliderTooltipNPETest.java
@@ -88,6 +88,13 @@ public class SliderTooltipNPETest {
     }
 
     private void dragSliderAfterTooltipDisplayed(int dragDistance) throws Exception {
+        Util.runAndWait(() -> {
+            // Click somewhere in the Stage to ensure that it is active
+            robot.mouseMove((int)(scene.getWindow().getX() + scene.getX()),
+                            (int)(scene.getWindow().getY() + scene.getY()));
+            robot.mouseClick(MouseButton.PRIMARY);
+        });
+
         Thread.sleep(1000); // Wait for slider to layout
 
         Util.runAndWait(() -> {
```

2023-06-13 05:48 UTC, karthikpandelu commented
Thanks for the suggestion @kevinrushforth. Made changes according to your comments. Please check.

2023-06-13 13:00 UTC, kevinrushforth approved these changes

2023-06-13 13:32 UTC, karthikpandelu commented
/integrate

2023-06-13 13:33 UTC, closed without merging