8301763: Adding children to wrong index leaves inconsistent state in Parent#childrenSet
openjdk/jfx pull request #1136
Opened 2023-05-15 12:49 UTC by lukostyra

This issue happened because `childSet` member of Parent was modified during `onProposedChange()` call - that call did not recognize negative indexes as invalid, which caused an exception when actually adding the Node to a List.

This seemed like the simplest solution which doesn't rework a lot of code underneath. Exceptions coming from a backing list/collection technically are handled by `VetoableListDecorator`'s try-catch clauses, however `VetoableListDecorator` does not provide an interface to react when such an exception happens - without it we cannot revert `childSet` back to its original state.

2023-05-15 15:24 UTC, hjohn commented
I think it may be better to do this check in the callers of `onProposedChange` (using the assertions in `Objects` to test for valid indices.).  This will also allow to check when the index is too large, which is a similar problem. Note that you can't do the "too large" check in `onProposedChange` as for `remove`, `size()` would be too large, while for `add(int, E)` `size()` would still be valid.

Also, for the cases where `onProposedChange` is called with multiple sets of indices, those don't need a check (they come from calls like `removeAll`, which will all be valid).

Furthermore, it should be an `IndexOutOfBoundsException` as this is specified by the `List` interface.

I noticed there are similar problems in `ObservableListWrapper`.  This method for example:

    @Override
    protected void doAdd(int index, E element) {
        if (elementObserver != null)
            elementObserver.attachListener(element);
        backingList.add(index, element);
    }

This will attach a listener to the element (assuming it is an `Observable`) even if `backingList.add` fails...

2023-05-16 07:03 UTC, lukostyra commented
Thanks for your notes, I was wondering if there was a better approach. I'll rework the patch.

2023-05-17 16:40 UTC, lukostyra commented
As a small note, the issue is solved with current patches, however I think the best solution would be what I mentioned in the original PR message - an interface in `VetoableListDecorator` which would let us "roll-back" any changes from `onProposedChange` (ex. revert `childSet` to original state) when backing lists throw an exception. This would require a more thorough analysis of what bits use `VetoableListDecorator` and if any roll-backs are necessary there in addition to Parent code.

2023-05-17 22:54 UTC, hjohn requested changes
I think `ObservableListWrapper#remove(int, int)` also needs a check index check, or it may end up remove some items and then throw an exception (exceptions thrown from collections should not modify its state).

2023-05-17 22:54 UTC, hjohn commented on modules/javafx.base/src/main/java/com/sun/javafx/collections/VetoableListDecorator.java
>          onProposedChange(Collections.unmodifiableList(new ArrayList<>(col)), 0, size());
It's good to make it explicit.  It already threw NPE because of `new ArrayList<>(col)`, so this is not a change.

2023-05-17 22:54 UTC, hjohn commented on modules/javafx.base/src/main/java/com/sun/javafx/collections/VetoableListDecorator.java
> +        Objects.requireNonNull(c);
Looks like a good change, if `c` was `null` and the backing list was empty, this would not throw NPE, but now it does.

2023-05-17 22:54 UTC, hjohn commented on modules/javafx.graphics/src/test/java/test/javafx/scene/ParentTest.java
> +
I think you should also add tests for the `null` cases, if they aren't part of this test already.

2023-05-17 23:15 UTC, hjohn commented
> As a small note, the issue is solved with current patches, however I think the best solution would be what I mentioned in the original PR message - an interface in `VetoableListDecorator` which would let us "roll-back" any changes from `onProposedChange` (ex. revert `childSet` to original state) when backing lists throw an exception. This would require a more thorough analysis of what bits use `VetoableListDecorator` and if any roll-backs are necessary there in addition to Parent code.

I'm not convinced this is needed or desirable. The `VetoableListDecorator` is currently set up that its owner can already make "preparations" for the change when it knows it won't veto it (there can be only one vetoer, making this reasonable).  Furthermore, it has the wrapped list under its own control, so it knows what to expect (no exceptions can occur (after this fix) if it decides not to veto).

A roll back mechanism would just complicate the code for very little benefit (a correct FX application won't run into these situations, you'll only be likely to encounter them during development). The whole mechanism surrounding the children list and bad additions should be seen as a best effort early warning system (like ConcurrentModificationExeption).

With this fix I don't see any other ways you could get it in a bad state.

2023-05-22 14:30 UTC, hjohn approved these changes

2023-05-24 11:24 UTC, kevinrushforth approved these changes
Looks good.

2023-05-24 11:35 UTC, lukostyra commented
/integrate

2023-05-24 11:37 UTC, hjohn commented
/sponsor

2023-05-24 11:38 UTC, closed without merging