8090267: JFXPanel Input Problem
openjdk/jfx pull request #1169
Opened 2023-07-04 05:54 UTC by prsadhuk

When Japanse (IME on) is inputted to the TextFIeld, which is on JFXPanel, 
small window for inputting appears on top-left side of screen

![image](https://github.com/openjdk/jfx/assets/43534309/65833d59-528e-4087-9992-9f86b8b8c47f)

For swing-interop case, WmImeStartComposition starts composition in native ImmSetCompositionWindow window as "m_useNativeCompWindow" below is true for FX
https://github.com/openjdk/jdk/blob/514816ed7d7dea1fb13d32b80aef89774bee13d3/src/java.desktop/windows/native/libawt/windows/awt_Component.cpp#L3957

m_useNativeCompWindow is true because during sun.awt.im.InputContext#focusGained() calls activateInputMethod which calls WInputMethod.activate() which calls haveActiveClient() which checks for
clientComponent.getInputMethodRequests().
Now, in JFXPanel, getInputMethodRequests() returns null as setEmbeddedScene() is not called yet.
Since getInputMethodRequests() returns null, haveActiveClient() is false which calls enableNativeIME() with 1 [thereby native composition window is enabled]
https://github.com/openjdk/jdk/blob/514816ed7d7dea1fb13d32b80aef89774bee13d3/src/java.desktop/windows/classes/sun/awt/windows/WInputMethod.java#L316

Proposed fix is to ensure there is an active client "initially" so that enableNativeIME() is called with 0 and no native compostion window is shown.
getInputMethodRequests() is called in setEmbeddedScene() so as to make sure getInputMethodRequest() is initialised to correct "InputMethodSupport.InputMethodRequestsAdapter.fxRequests" object and not NULL.

AFter fix
![image](https://github.com/openjdk/jfx/assets/43534309/ec3d8343-9295-4950-885b-f9983b9b017a)

2023-07-26 08:39 UTC, ctipper commented
I'm a client side developer trying to add a custom input method event handler to my app and I have noticed this problem on Windows with the native client. These APIs don't seem to have an great deal of online documentation and I can't even get it to work in macOS. Sorry but I don't have privileges for JIRA.

2023-07-27 13:53 UTC, prsadhuk commented
ping?

2023-07-27 16:59 UTC, andy-goryachev-oracle commented
I would love to review this, but for some reason, I could not get Japanese IME to work on my windows 11...

2023-08-07 07:14 UTC, prsadhuk commented
> I would love to review this, but for some reason, I could not get Japanese IME to work on my windows 11...

Does it work now? 
or Can anyone else review this please?

2023-08-17 19:51 UTC, andy-goryachev-oracle commented
This PR has been outstanding for a long time, please sync with the latest master.

When I merged the latest master in my own local branch, I see a number of issues on Windows 11 with Japanese IME:

1. type simple Romaji sequences (arigatou):

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot read field "x" because "location" is null
	at javafx.graphics/com.sun.javafx.text.PrismTextLayout.getCaretShape(PrismTextLayout.java:379)
	at javafx.graphics/javafx.scene.text.Text$TextAttribute$11.computeValue(Text.java:1823)
	at javafx.graphics/javafx.scene.text.Text$TextAttribute$11.computeValue(Text.java:1)
	at javafx.base/javafx.beans.binding.ObjectBinding.get(ObjectBinding.java:168)
	at javafx.base/javafx.beans.binding.ObjectExpression.getValue(ObjectExpression.java:49)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.get(ObjectPropertyBase.java:133)
	at javafx.controls/javafx.scene.control.skin.TextFieldSkin.lambda$4(TextFieldSkin.java:247)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(ObjectPropertyBase.java:234)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base/javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:192)
	at javafx.graphics/javafx.scene.text.Text.doGeomChanged(Text.java:842)
	at javafx.graphics/javafx.scene.text.Text$1.doGeomChanged(Text.java:159)
	at javafx.graphics/com.sun.javafx.scene.shape.TextHelper.geomChangedImpl(TextHelper.java:106)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.geomChanged(NodeHelper.java:139)
	at javafx.graphics/javafx.scene.text.Text.needsTextLayout(Text.java:267)
	at javafx.graphics/javafx.scene.text.Text.needsFullTextLayout(Text.java:262)
	at javafx.graphics/javafx.scene.text.Text$3.invalidated(Text.java:463)
	at javafx.base/javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
	at javafx.base/javafx.beans.property.StringPropertyBase$Listener.invalidated(StringPropertyBase.java:231)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base/javafx.beans.binding.StringBinding.invalidate(StringBinding.java:181)
	at javafx.base/com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:52)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.controls/javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1496)
	at javafx.controls/javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1500)
	at javafx.controls/javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(TextInputControl.java:1439)
	at javafx.controls/javafx.scene.control.TextInputControl.lambda$0(TextInputControl.java:176)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.controls/javafx.scene.control.TextInputControl$ContentBase.fireValueChangedEvent(TextInputControl.java:149)
	at javafx.controls/javafx.scene.control.TextField$TextFieldContent.insert(TextField.java:88)
	at javafx.controls/javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:1301)
	at javafx.controls/javafx.scene.control.TextInputControl.updateContent(TextInputControl.java:609)
	at javafx.controls/javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:601)
	at javafx.controls/javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:560)
	at javafx.controls/javafx.scene.control.skin.TextInputControlSkin.handleInputMethodEvent(TextInputControlSkin.java:785)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8875)
	at javafx.graphics/javafx.scene.Scene.processInputMethodEvent(Scene.java:2322)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.inputMethodEvent(Scene.java:2725)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedScene.lambda$9(EmbeddedScene.java:332)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedScene.lambda$8(EmbeddedScene.java:330)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$11(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$10(PlatformImpl.java:455)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$4(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

2023-08-17 19:57 UTC, andy-goryachev-oracle commented
issue 2:
configure Japanese IME for Hiragana input, such that the following icons are shown in the task bar:

![Screenshot 2023-08-17 125430](https://github.com/openjdk/jfx/assets/107069028/3c0971f9-8fe5-4b86-8332-8330ca25c966)

then launch the test app and type 'a'.

I see two hiragana ああ characters instead of one あ:

![Screenshot 2023-08-17 125206](https://github.com/openjdk/jfx/assets/107069028/52553335-686d-4efa-8833-8b722aa94846)

2023-08-17 19:58 UTC, andy-goryachev-oracle commented
issue 3: further typing and editing (using BACKSPACE key) results in a series of exceptions:

```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at javafx.base/com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:88)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:314)
	at javafx.graphics/javafx.scene.Parent.updateCachedBounds(Parent.java:1705)
	at javafx.graphics/javafx.scene.Parent.recomputeBounds(Parent.java:1649)
	at javafx.graphics/javafx.scene.Parent.doComputeGeomBounds(Parent.java:1502)
	at javafx.graphics/javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.graphics/javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3301)
	at javafx.graphics/javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:166)
	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:117)
	at javafx.graphics/javafx.scene.Node.updateGeomBounds(Node.java:3812)
	at javafx.graphics/javafx.scene.Node.getGeomBounds(Node.java:3774)
	at javafx.graphics/javafx.scene.Node.computeLocalBounds(Node.java:3828)
	at javafx.graphics/javafx.scene.Node.updateLocalBounds(Node.java:3858)
	at javafx.graphics/javafx.scene.Node.getLocalBounds(Node.java:3728)
	at javafx.graphics/javafx.scene.Node.updateTxBounds(Node.java:3876)
	at javafx.graphics/javafx.scene.Node.getTransformedBounds(Node.java:3668)
	at javafx.graphics/javafx.scene.Node$MiscProperties$2.computeBounds(Node.java:6770)
	at javafx.graphics/javafx.scene.Node$LazyBoundsProperty.get(Node.java:9749)
	at javafx.graphics/javafx.scene.Node$LazyBoundsProperty.get(Node.java:1)
	at javafx.graphics/javafx.scene.Node.getBoundsInParent(Node.java:3361)
	at javafx.controls/javafx.scene.control.skin.TextFieldSkin.getCharacterBounds(TextFieldSkin.java:533)
	at javafx.controls/javafx.scene.control.skin.TextInputControlSkin$11.getTextLocation(TextInputControlSkin.java:351)
	at javafx.graphics/javafx.scene.Scene$InputMethodRequestsDelegate.getTextLocation(Scene.java:4169)
	at javafx.swing/javafx.embed.swing.InputMethodSupport$InputMethodRequestsAdapter.getTextLocation(InputMethodSupport.java:61)
	at java.desktop/sun.awt.im.InputMethodContext.getTextLocation(InputMethodContext.java:279)
	at java.desktop/sun.awt.windows.WInputMethod$1.run(WInputMethod.java:616)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 4
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at javafx.base/com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:88)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:314)
	at javafx.graphics/javafx.scene.Parent.updateCachedBounds(Parent.java:1705)
	at javafx.graphics/javafx.scene.Parent.recomputeBounds(Parent.java:1649)
	at javafx.graphics/javafx.scene.Parent.doComputeGeomBounds(Parent.java:1502)
	at javafx.graphics/javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.graphics/javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3301)
	at javafx.graphics/javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:166)
	at javafx.graphics/com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:117)
	at javafx.graphics/javafx.scene.Node.updateGeomBounds(Node.java:3812)
	at javafx.graphics/javafx.scene.Node.getGeomBounds(Node.java:3774)
	at javafx.graphics/javafx.scene.Node.computeLocalBounds(Node.java:3828)
	at javafx.graphics/javafx.scene.Node.updateLocalBounds(Node.java:3858)
	at javafx.graphics/javafx.scene.Node.getLocalBounds(Node.java:3728)
	at javafx.graphics/javafx.scene.Node.updateTxBounds(Node.java:3876)
	at javafx.graphics/javafx.scene.Node.getTransformedBounds(Node.java:3668)
	at javafx.graphics/javafx.scene.Node$MiscProperties$2.computeBounds(Node.java:6770)
	at javafx.graphics/javafx.scene.Node$LazyBoundsProperty.get(Node.java:9749)
	at javafx.graphics/javafx.scene.Node$LazyBoundsProperty.get(Node.java:1)
	at javafx.graphics/javafx.scene.Node.getBoundsInParent(Node.java:3361)
	at javafx.controls/javafx.scene.control.skin.TextFieldSkin.getCharacterBounds(TextFieldSkin.java:533)
	at javafx.controls/javafx.scene.control.skin.TextInputControlSkin$11.getTextLocation(TextInputControlSkin.java:351)
	at javafx.graphics/javafx.scene.Scene$InputMethodRequestsDelegate.getTextLocation(Scene.java:4169)
	at javafx.swing/javafx.embed.swing.InputMethodSupport$InputMethodRequestsAdapter.getTextLocation(InputMethodSupport.java:61)
	at java.desktop/sun.awt.im.InputMethodContext.getTextLocation(InputMethodContext.java:279)
	at java.desktop/sun.awt.windows.WInputMethod$1.run(WInputMethod.java:616)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:77 [...]

2023-08-17 19:59 UTC, andy-goryachev-oracle commented
The good new is that the IME box appears at the right spot :-)

2023-08-17 21:19 UTC, andy-goryachev-oracle commented
The bad news is that without the fix, the IME UI works correctly - the only issue is that it is in the wrong position (as seems to be using a different Look and Feel).  No exceptions, no duplicate symbols, no caret positioning issues.

Tested on Windows 11 Pro, 22H2 os build 22621.1992, Windows Feature Experience Pack 1000.22644.1000.0

2023-08-17 21:20 UTC, andy-goryachev-oracle requested changes
The fix introduced a number of issues.

2023-08-21 04:25 UTC, prsadhuk commented
I am not able to reproduce issue1,2,3 in windows 10 testing

Issue2 in my system

![image](https://github.com/openjdk/jfx/assets/43534309/603c2a92-fcd6-4e70-a2c4-fb52d774ad37)

Also, I tried adding and backspacing/deleting typed characters without any issue...
Seems like this issue is specific to Windows11 and maynot be related to swing-interop

2023-08-21 16:19 UTC, andy-goryachev-oracle commented
could we try this on another window 11 box?

2023-08-21 20:52 UTC, beldenfox commented
I tried this on my Windows 11 setup. I can reproduce all of the problems @andy-goryachev-oracle was seeing but the behavior is erratic so I'm having difficulty coming up with a precise set of steps.

You might try this:
- set keyboard to Japanese, half-width alphanumeric
- launch the test app
- click in the TextField to establish focus (focus is not working as expected for me)
- type two 'a' characters
- switch to Hirigana
- type 'a'

On my system the input sequence displays doubled aaあaaあ. At this point the TextField is confused, if I commit and start moving the cursor around it treats the final あaaあ sequence as one character. Various bad behavior follows.

I can also get into a state where exceptions are being thrown but haven't figured out precisely how. Seems to happen most when I switch to Hiragana and start typing quickly...

Without Swing in the picture none of these problems occur.

2023-10-17 06:28 UTC, closed without merging

2023-12-29 18:54 UTC, beldenfox commented
It turns out this PR didn't introduce new problems, it just exposed existing ones. The AWT EventQueue thread is calling into the InputMethodRequests at the same time as the JavaFX thread is updating and drawing the text field. If the timing is right (or wrong) both threads can trigger glyph layout in the same Text object at the same time. The result is the sort of erratic behavior seen here.

I've entered [JDK-8322784](https://bugs.openjdk.org/browse/JDK-8322784).