8309558: Create implementation of NSAccessibilityCheckBox protocol
openjdk/jfx pull request #1184
Opened 2023-07-23 20:35 UTC by azuev-java

also
8309629: Create implementation of NSAccessibilityRadioButton protocol

Create implementation of NSAccessibilityCheckBox and NSAccessibilityRadioButton protocols
Add workaround for the wrong focus owner announcement with radio buttons
Add workaround for wrong magnifier text on buttons

2023-07-23 20:37 UTC, azuev-java commented
/issue add JDK-8309629

2023-07-24 11:53 UTC, kevinrushforth commented
/reviewers 2

2023-08-04 11:39 UTC, kevinrushforth commented
Reviewers @arapte @kevinrushforth

2023-08-04 13:27 UTC, kevinrushforth approved these changes
Code changes look good. I tested it on macOS 13.3.1 and VoiceOver output was as expected.

2023-08-06 13:35 UTC, arapte requested changes
Providing a minor comment for a warning.
Also noticed that, with this change tab are read as radio button. [ Tested with ensemble ]

<img width="646" alt="Screenshot 2023-08-06 at 3 23 35 PM" src="https://github.com/openjdk/jfx/assets/11330676/1d9ade44-2305-4f13-afe3-2d586934a918">

2023-08-07 14:11 UTC, kevinrushforth requested changes
> Also noticed that, with this change tab are read as radio button. [ Tested with ensemble ]

That seems like a bug.

2023-08-07 14:11 UTC, kevinrushforth commented on modules/javafx.graphics/src/main/native-glass/mac/a11y/AccessibleBase.m
> +    if (env == NULL) return NULL;
Good catch. This should probably be changed to: `return NO;`

2023-08-14 18:47 UTC, azuev-java commented on modules/javafx.graphics/src/main/native-glass/mac/a11y/AccessibleBase.m
> +    if (env == NULL) return NULL;
Fixed.

2023-08-14 18:53 UTC, azuev-java commented
> Providing a minor comment for a warning. Also noticed that, with this change tab are read as radio button. [ Tested with ensemble ]
> 
> <img alt="Screenshot 2023-08-06 at 3 23 35 PM" width="646" src="https://user-images.githubusercontent.com/11330676/258645623-1d9ade44-2305-4f13-afe3-2d586934a918.png">

That seems to require the proper implementation of TAB_GROUP with the new API - mixing old and new API does not work here since in the existing code the accessible type reported is radio button but because parent encloses them in a tab group content it gets translated as tab item. Changing type to tab item without implementing tab group makes it loose the "Tab x out of y" notion so it is not the correct way to go. Commented out that assignment until tab group is implemented.

2023-08-16 18:07 UTC, kevinrushforth approved these changes

2023-08-17 20:16 UTC, azuev-java commented
/integrate

2023-08-17 20:26 UTC, kevinrushforth commented
/sponsor

2023-08-17 20:28 UTC, closed without merging