8322544 Parts of SG no longer update during rendering - overlapping - culling - dirty
openjdk/jfx pull request #1310
Opened 2023-12-21 12:33 UTC by FlorianKirmaier

In some situations, a part of the SG is no longer rendered.
I created a test program that showcases this problem.

Explanation:

This can happen, when a part of the SG, is covered by another Node.
In this part, one node is totally covered, and the other node is visible.

When the totally covered Node is changed, then it is marked dirty and it's parent, recursively until an already dirty node is found.
Due to the Culling, this totally covered Node is not rendered - with the effect that the tree is never marked as Clean.

In this state, a Node is Dirty but not It's parent. Based on my CodeReview, this is an invalid state which should never happen.

In this invalid state, when the other Node is changed, which is visible, then the dirty state is no longer propagated upwards - because the recursive "NGNode.markTreeDirty" algorithm encounters a dirty node early.

This has the effect, that any SG changes in the visible Node are no longer rendered. Sometimes the situation repairs itself.

Useful parameters for further investigations:
-Djavafx.pulseLogger=true
-Dprism.printrendergraph=true
-Djavafx.pulseLogger.threshold=0

PR:
This PR ensures the dirty flag is set to false of the tree when the culling is used.
It doesn't seem to break any existing tests - but I'm not sure whether this is the right way to fix it.
It would be great to have some feedback on this solution - maybe guiding me to a better solution.

I could write a test, that just does the same thing as the test application, but checks every frame that these nodes are not dirty - but maybe there is a better way to test this.

2023-12-21 12:53 UTC, FlorianKirmaier commented
*Fixed wrong ticket-number in title and commit*

2023-12-21 14:46 UTC, kevinrushforth commented
/reviewers 2

2023-12-21 15:13 UTC, kevinrushforth reviewed
I'd like to see an automated (probably robot-based) test, if it is feasible.

This will need careful review. 

Reviewers: @arapte @lukostyra

2023-12-21 15:46 UTC, FlorianKirmaier commented
If someone who understands the rendering could provide some feedback on what is happening - than I can probably make a better fix, and write a reasonable unit-test for this bug.
The current fix is a bit suboptimal - because the call to clean-dirty is O(n) and might be called n time - leading to O(n^2)

2023-12-22 08:34 UTC, hjohn commented
The fully covered node which was dirty is now marked clean in the PR when it is culled.  Now that it is clean, what happens when it is uncovered (being careful not to change it in any other way)?  Does it get rendered correctly, or does it miss the last change made to it while it was fully covered?

If that works correctly still, then I think this is the right fix.  Culling the node is (IMHO) the same as rendering it (there is nothing to render) so it should be clean after being culled.

2023-12-22 12:54 UTC, FlorianKirmaier commented
It is worth noting that the idea of cleaning the dirty tree, for the culled node, is also done at line `NGNode:1414`, but for some reason, it doesn't catch the case from this bug.

2024-01-16 11:07 UTC, FlorianKirmaier commented
I tried out a bit, by removing the clipping area in my test program.
I added the changed program to the ticket.
Didn't notice anything wrong.
There are probably many ways to test for regressions. 

Can't guarantee that there are no other cases that go wrong - but if something doesn't work, then it happens more rarely than this one.

2024-01-23 11:49 UTC, FlorianKirmaier commented on .idea/jpa-buddy.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Removed the accidental change!

2024-03-13 09:27 UTC, lukostyra commented
> Maybe we could make snapshot based tests? That should work on all platforms, right?

We have a whole suite of tests which use similar methods to perform checks, called robot tests. Since you want to check if a node was properly updated, and the best way to do that seems to be checking RGB values, I think a test for this case belongs right there.

You could use robot utility to check color values of specific pixels on the screen. I think the best way to go about it would be to do something similar to what your test bug apps do (the ones attached to the JBS issue). Ideally I would try and look for first some form of confidence check (if correct controls are "on" and "off"), then progressing the animation and seeing if controls updated as intended.

All robot tests are located in `tests/system/src/test/java/test/robot` and then they follow package names. I'm not 100% sure where this test should go though (I assume `.../javafx/scene`?).

2024-04-26 16:03 UTC, eduardsdv commented
I analysed the bug and can confirm the fix.
I summarized it in the following table. 
First column is the node structure, the others the steps: update nodes, render, update nodes, render, ...

| Nodes (L - left and R - right) / Steps			| 1st -> update Circles 	| 2nd -> render 	| 3rd -> update Lines 	| 4th -> render |
|-|-|-|-|-|
|HBox					|dirty				|clearDirty		|dirty				|clearDirty			
|HBox >StackPane-L			|dirty				|clearDirty		|dirty				|clearDirty
|HBox >StackPane-L > Group-L			|dirty				|clearDirty		|dirty				|clearDirty
|HBox >StackPane-L > Group-L >Line-L		|					|				|dirty				|clearDirty
|HBox >StackPane-L > Group-L >Circle-L		|dirty				|clearDirty	    	|
|HBox >StackPane-R			|dirty				|clearDirty  *1		|				|	*3
|HBox >StackPane-R > Group-R			|dirty				|dirty			|dirty  
|HBox >StackPane-R > Group-R > Line-R		|					|				|dirty  *2				|dirty
|HBox >StackPane-R > Group-R > Circle-R		|dirty				|dirty			|dirty				|dirty


*1: > no culling bits for first dirty region (Circle-L) -> skip children -> clearDirty() is not called on children
     > no root path for the second dirty region (Circle-R) -> no rendering and root.clearDirtyTree() stops on StackPane-R (the children stay dirty: Group-R and Circle-R)
	
*2: > Line-R.markTreeDirty() skips marking of further parents because Group-R is already dirty -> the StackPane-R stays clean

*3: > the dirty regions are not collected because the StackPane-R is clean -> Line-R is not rendered and the dirty-flag is not reset

-------
The error is that ``clearDirty()`` is not called in the second step on the children of StackPane-R (see *1). Subsequent changes in Line-R and Circle-R are not propagated to the root node because Group-R is already dirty (see *2) and therefore StackPane-R remains clean. The last changes are therefore ignored in the next rendering phase (see *3).

-------
We can simply say: **the dirty flags must be deleted on all nodes after rendering**.

If this is true, the test can simply check this instead of screenshots or similar.

2024-04-29 16:19 UTC, eduardsdv commented
After further investigation and testing I would suggest to remove all ``clearDirty()`` and ``clearDirtyTree()`` calls and put only one clear-dirty pass after rendering is done (at the end of ``ViewerPainter.paintImpl(final Graphics backBufferGraphics)``).

Since the ``markDirty()`` method does both, sets the dirty flag and propagates it to the ancestor nodes, it is better if there is only one method for deleting the dirty flag from the node and all its children. Therefore, I would remove the ``clearDirtyTree()`` method and move its content to the ``clearDirty()`` method.

This way we can guarantee that all dirty flags are removed after the rendering is completed.
We also guarantee that a clean parent with dirty children will never occur (the bug this PR addresses).

Furthermore, my quick test shows that fewer ``clearDirty()`` calls are required in the new version. Bonus: We are even faster.

````java
    public void clearDirty() {
        if (dirty != DirtyFlag.CLEAN || childDirty) {
            dirty = DirtyFlag.CLEAN;
            childDirty = false;
            dirtyBounds.makeEmpty();
            dirtyChildrenAccumulated = 0;

            if (this instanceof NGGroup) {
                List<NGNode> children = ((NGGroup) this).getChildren();
                for (NGNode child : children) {
                    child.clearDirtyTree_();
                }
            }
        }

        if (getClipNode() != null) {
            getClipNode().clearDirty();
        }
    }

````

2024-05-03 10:41 UTC, eduardsdv commented
I added a test that shows that the @FlorianKirmaier's fix works. You can start it with: `gradlew -PFULL_TEST=true :systemTests:test --tests NGNodeDirtyFlagTest`.

To avoid such errors in the future, I would still suggest the refactoring, which I wrote about in my last comment.

@kevinrushforth and @arapte please review.

2024-05-06 14:15 UTC, eduardsdv commented
I created an alternative solution for this bug. See PR: https://github.com/openjdk/jfx/pull/1451

2024-05-11 13:06 UTC, kevinrushforth commented
/csr unneeded

2024-05-11 19:41 UTC, kevinrushforth commented
/csr unneeded

2024-05-17 12:36 UTC, FlorianKirmaier commented
Sorry for creating the CSR, it was an accident.

Now that Eduard has both created an alternative solution, but also has reviewed that this solution is correct, and provided an unit-test - I think this (or the other) PR is ready to move forwards.

@kevinrushforth 
What do you think?

This is still quite a fundamental bug which is probably quite prevalent, 
because when it happens it is really hard to notice it.
But it probably happens more often than we think.

2024-05-18 14:13 UTC, kevinrushforth commented
> Sorry for creating the CSR, it was an accident.

No problem.

> Now that Eduard has both created an alternative solution, but also has reviewed that this solution is correct, and provided an unit-test - I think this (or the other) PR is ready to move forwards.
> 
> @kevinrushforth What do you think?

Yes, I've asked @arapte to be the primary reviewer on this. I'll leave it to his judgment as to which of the two approaches to take forward.

2024-06-17 07:14 UTC, eduardsdv commented
keep alive

2024-06-26 07:42 UTC, eduardsdv commented
@arapte Please review.

2024-07-04 12:52 UTC, kevinrushforth commented
@FlorianKirmaier since it looks like we are going with PR #1451 as the solution, please close this PR (or move it to Draft until #1451 is integrated and then close it).

2024-07-09 15:14 UTC, kevinrushforth requested changes
This PR should be closed now that PR #1451 is integrated.

2024-07-11 09:03 UTC, closed without merging