8330590: TextInputControl: previous word fails with Bhojpuri characters
openjdk/jfx pull request #1444
Opened 2024-04-19 19:44 UTC by andy-goryachev-oracle

This change replaces Character.isLetterOrDigit(char) which fails with surrogate characters with  Character.isLetterOrDigit(int).

2024-04-24 20:30 UTC, kevinrushforth commented
@karthikpandelu Can you review this? We'll also need a review by a "R"eviewer.

2024-04-29 15:50 UTC, andy-goryachev-oracle commented
> Is this expected?

I think it might be a bug - even though it's unclear how many words the text "𑂦𑂷𑂔𑂣𑂳𑂩𑂲" contains, I would not expect it to go to the beginning of that segment.

I suspect the code in `TextInputControl.endOfNextWord(boolean)` is incorrect, and it needs a deeper re-write than the naive replacement with `isLetterOrDigit()`.

2024-04-29 16:51 UTC, andy-goryachev-oracle commented
I think we need to fix endOf/nextWord as well, as the logic seems to be breaking with the surrogate pairs:

![Screenshot 2024-04-29 at 09 48 33](https://github.com/openjdk/jfx/assets/107069028/02a33046-6d15-45c1-a294-57bf609bdc8d)


The issue can also be seen with Awadhi: अवधी/औधी

2024-04-29 21:27 UTC, andy-goryachev-oracle commented
Looking at the "next word" functionality across different applications on different platforms, it appears to be a wide variety of behaviors.

One vendor appears to be quite consistent - Microsoft.  Its word, word pad, notepad work exactly the same, with Word working the same across macOS and Win11.

JavaFX TextArea is inconsistent (by design) between macOS and Win11, but also is inconsistent with Swing's JTextArea.

If I were to fix the behavior (if we decide to fix the behavior of the nextWord function, that is), I would make it consistent with MS Word, but let's discuss.

For reference, here is the result of my testing.  Initially, the caret is placed at index 0 and the numbers in parentheses denote successive caret positions after ctrl-RIGHT (option-RIGHT) key presses.  An underline denotes a space, and a (nl) denotes a newline.

```
source
_english_english_eng:_end,_eng:_(nl)
(nl)
_eng


BreakIterator.getWordInstance()
_(1)english(2)_(3)english(4)_(5)eng(6):(7)_(8)end(9),(10)_(11)eng(12):(13)_(14)(nl)
(15)(nl)
(16)_(17)eng


text area (mac)
_english(1)_english(2)_eng(3):(4)_end(5),(6)_eng(7):(8)_(nl)
(9)(nl)
(10)_eng(11)


ms word (mac) 16.84 24041420 consistent with win11
_(1)english_(2)english_(3)eng(4):_(5)end(6),_(7)eng(8):_(9)(nl)
(10)(nl)
(11)_(12)eng(13)


text edit (mac)
_english(1)_english(2)_eng(3):_end(4),_eng(5):_(nl)
(nl)
(nl)_eng(6)


chrome (mac) <div contenteditable=true>
&nbsp;english(1)_english(2)_eng(3):(4)_end(5),(6)_eng(7):(8)_<br>
(9)<br>
_(10)eng(11)


eclipse (mac)
_(1)english_(2)english_(3)eng(4):_(5)end(6),_(7)eng(8):_(9)(nl)
(10)(nl)
(11)_(12)eng


JTextArea (mac)
_(1)english_(2)english_(3)eng(4):_(5)end(6),_(7)eng(8):_(9)(nl)
(nl)
_(10)eng


ms word 365 ver 2302 build 16.0.16130.20942 (win 11)
same as notepad (win 11)
same as wordpad (win 11)
_(1)english_(2)english_(3)eng(4):_(5)end(6),_(7)eng(8):_(9)(nl)
(10)(nl)
(11)_(12)eng


TextArea (win11)
_(1)english_(2)english_(3)eng(4):_(5)end(6),_(7)eng(8):_(9)(nl)
(10)(nl)
_(11)eng
```

2024-04-29 21:28 UTC, andy-goryachev-oracle commented
@aghaisas would you please take a look at this also?

2024-05-08 17:28 UTC, andy-goryachev-oracle commented
I've created https://bugs.openjdk.org/browse/JDK-8331951 to deal with the "next word" function issues.

2024-05-17 11:59 UTC, arapte requested changes
Fix looks good, providing minor comments.

2024-05-17 15:31 UTC, andy-goryachev-oracle commented on modules/javafx.controls/src/main/java/javafx/scene/control/TextInputControl.java
> +    private static boolean isLetterOrDigit(String text, int ix, int len) {
fixed, thank you

2024-05-17 15:33 UTC, andy-goryachev-oracle commented on modules/javafx.controls/src/main/java/javafx/scene/control/TextInputControl.java
> +        }
I prefer to keep one statement per line; the checks are needed here.

2024-05-17 17:58 UTC, arapte approved these changes

2024-05-17 18:29 UTC, karthikpandelu approved these changes

2024-05-20 14:53 UTC, andy-goryachev-oracle commented
/integrate

2024-05-20 14:54 UTC, closed without merging