8273485: Deadlock when also using Swing and exiting Fullscreen on Mac
openjdk/jfx pull request #622
Opened 2021-09-08 10:37 UTC by FlorianKirmaier

When using Swing it's possible to generate a Deadlock.
 It's related to the nested eventloop started in enterFullScreenExitingLoop - and the RenderLock aquired when using setView in Scene.
 Sample Programm and Threaddump are added to the ticket.

Removing the nested loop fixes the Problem. 
I hope this doesn't have any side effect - so far i don't know of any.

2021-09-08 12:07 UTC, kevinrushforth commented
/reviewers 2

2021-09-08 12:14 UTC, kevinrushforth requested changes
I am almost certain that this proposed fix will cause problems. At the very least we will now have mismatched enter / exit nested loop calls. The nested loop for full screen on Mac was done for a reason, so you will need to track down what that reason is and either verify that it is no longer needed or else solve that some other way.

Also, you don't explain why removing the nested event loop is the right fix for the deadlock.

Finally, once you address the above two points, you will need to turn the test program attached to the JBS bug into an automated test.

2021-09-09 07:55 UTC, FlorianKirmaier commented
Thank you for the feedback - I will start writing an unit test for it because it will help on all further development regarding this issue.

2021-09-13 14:34 UTC, FlorianKirmaier commented
I've now added a unit test.

I've adapted the solution to entirely remove the nested event loop, for the fullscreen. So far everything seems to work.
I've tested it with a simple application to check how the fullscreen behaves.
The logic seems to be added before the beginning of the VCS / 2013
Is there away to look into the history before 2013? Maybe there is a hint, why this was added.
Otherwise i would guess that it is not too important, and it is just an unnecessary overcomplicated solution.

2021-09-17 12:44 UTC, kevinrushforth requested changes
> I've adapted the solution to entirely remove the nested event loop, for the fullscreen. So far everything seems to work.
> I've tested it with a simple application to check how the fullscreen behaves.
> The logic seems to be added before the beginning of the VCS / 2013
> Is there away to look into the history before 2013? Maybe there is a hint, why this was added.

I tracked down the bug fix that added the nested event loop (looking at the history of the closed-source changes, since this fix was done prior to open-sourcing glass). It was added to fix [JDK-8126842](https://bugs.openjdk.java.net/browse/JDK-8126842).

As I suspected, the nested even loop is still necessary. If you run the test program attached to JDK-8126842 with your patch applied, make the window full-screen using the green button, then click the close button, the program will terminate with an exception.

2021-09-17 12:51 UTC, kevinrushforth commented
You can also see the exception with _any_ JavaFX program, enter full-screen with the green button, move the mouse to the upper-left corner to reveal the window decorations, and press the red button to exit the program.

I think you need to look for a different solution to your deadlock, one that preserves the existing nested event loop.

2021-09-21 11:22 UTC, FlorianKirmaier commented
Thank you for searching the original reason for the nested event loop!

I've now tested the class from the ticket, and for mit it works. The only strange thing is, that i get a "beep" sound when closing. Which isn't optimal but not the reported crash. Which is kinda unfortunate, because otherwise it might be easy to write a unit test.
Did you test the latest version of the PR?

I guess now i have to think of another fix, or on how do adapt this one.

2021-09-28 10:01 UTC, FlorianKirmaier commented
@kevinrushforth 
Did you test really test my change and was able to reproduce the JDK-8126842 with it?
On my system everything works - except the small "beep" sound.

After investigating it, I've made another small change - which fixes the beep sound. It also makes it closer to the implementation for iOS. I've changed the `waitUntilDone` value to true, when closing the window.

I think removing the nestedEventLoops should be preferred over another fix - in my experience the nested event loops are the cause of so many rare and very complicated bugs.

2021-10-14 14:27 UTC, kevinrushforth commented
I spoke too soon. I was running a few other manual tests, and your latest fix completely breaks the normal exit from full screen mode. To reproduce this:

1. Run `java hello.HelloFullscreenToggle`
2. Press the `Toggle Fullscreen` button to enter full-screen mode
3. Try to exit full screen mode, either by pressing the `ESC` key or by pressing the `Toggle Fullscreen` button again.
BUG: you can't exit full-screen mode.

2021-10-30 14:03 UTC, kevinrushforth reviewed
What version of macOS did you test on? I was running on 10.15.7 (Catalina). I just tried it on macOS 11.5 (Big Sur) and the exception does not happen, and on 10.14.6 (Mojave) where is does. To summarize, when calling `Platform.exit` while in full-screen mode:

macOS 10.14.6 : exception
macOS 10.15.7 : exception
macOS 11.5 : OK

2021-11-02 10:54 UTC, FlorianKirmaier commented on modules/javafx.graphics/src/main/native-glass/mac/GlassViewDelegate.m
> +            [[self->nsView window] toggleFullScreen:self];
With the previous version, I get a "beep" sound when closing a window.
But with the changed line, it works for me and I don't get any issues.
The beep sound also was the original reason, why I've removed the line.

2021-11-02 11:03 UTC, FlorianKirmaier commented
I've been using macOS 11.6. It is also not so easy for me to test another version.

I guess the exception can easily be "fixed" by checking whether the application is null, in the `Screen.initScreens` method. Should I change it this way?

2021-11-15 10:02 UTC, FlorianKirmaier commented
I've now added a check for null when calling the initScreens method. This should fix the null pointer exception.

2022-06-09 07:51 UTC, FlorianKirmaier commented on modules/javafx.graphics/src/main/native-glass/mac/GlassViewDelegate.m
> -            [GlassApplication enterFullScreenExitingLoop];
This was further discussed in the discussion below. So this is no longer up to date and therefore resolved.

2022-06-09 07:52 UTC, christianheilmann commented
How to proceed to get this PR reviewed?

2022-07-18 12:26 UTC, FlorianKirmaier commented
I've just merged it with the latest version in master.

2023-04-03 07:38 UTC, FlorianKirmaier commented
I would like to keep this PR. 
I've worked weeks on it, to make this work.
It's now been tested quite a long in production.

I understand that this is hard to test.
But It removes code, adds a unit test, fixes a reproducible bug, and has been used for a long time in a Real World application. 
That's usually the kind of PR we want to accept.

2023-05-09 07:58 UTC, FlorianKirmaier commented
Annually reminder that this pull request still exists.

Removing an unneeded NestedEventLoop is a huge reduction in complexity!

2023-07-04 14:02 UTC, closed without merging

2023-07-05 16:27 UTC, FlorianKirmaier commented
I guess there is no way to reopen pull requests, except creating new ones?

2023-07-07 19:40 UTC, beldenfox commented
I took a look at this since I'm trying to better understand the Mac fullscreen code (there's a bunch of cruft I would like to remove).

The stack trace in the original bug report confused me. In `WindowStage.setScene` the window be should taken out of fullscreen mode before setScene acquires the renderLock and sets the view to null. Exiting fullscreen is failing because at this point in the close process the stage is hidden and you can't change the fullscreen state of a stage while it's hidden (see `WindowStage.applyFullScreen`).

I think it's a bug in the core Java code that you can hide a fullscreen window without having it automatically exit fullscreen. Hiding a fullscreen window doesn't even work on the Mac since the OS just ignores the `orderOut:` call.

As an experiment I tweaked the Mac code to exit fullscreen when the window is hidden using exactly the same code as in _setView and it avoided the deadlock state reported in the original bug. I haven't done a full test run with the changes.

2023-07-07 19:48 UTC, andy-goryachev-oracle commented
> As an experiment I tweaked the Mac code to exit fullscreen when the window is hidden using exactly the same code as in _setView and it avoided the deadlock state reported in the original bug.

+1

2023-07-11 07:31 UTC, FlorianKirmaier commented
It's nice to see there are other ways to fix the problem.

The approach of this PR had the big advantage of highly reducing the complexity.
Nested Event Loops are highly cursed - and removing one of them probably solves complicated issues at once.
We had so many issues with nested event loops - and in my opinion - they should even be removed entirely in the long run.

2023-07-11 12:45 UTC, kevinrushforth commented
> I guess there is no way to reopen pull requests, except creating new ones?

There is, using the Skara `/open` command. In this case, I think the approach suggested by @beldenfox might be preferable.

2023-07-11 16:24 UTC, beldenfox commented
> The approach of this PR had the big advantage of highly reducing the complexity.

Nested event loops are complicated and I agree we should ditch them when we can. But in this case Apple saddled us and themselves with complexity by making fullscreen transitions asynchronous. I did a quick Google search and had no problem finding problems. The Electron folks discovered that if you call toggleFullscreen during the fullscreen transition you get "weird behavior (incl. phantom windows)" and I was able to reproduce this. Who knows what other strangeness can happen. Anything we do to make toggleFullscreen behave more synchronously reduces our exposure to Apple bugs (and synchronous behavior is what JavaFX expects) so I think we'll just have to grit our teeth and deal with the nested event loops.