8269115:WebView paste event contains old data
openjdk/jfx pull request #729
Opened 2022-02-08 11:13 UTC by jaybhaskar

Issue: The DataObject uses m_availMimeTypes as Vector of strings, and appending mime types in pasteboard operation like setPlainText, Hence it will append duplicate mime types in m_availMimeTypes , in this case the length clipboardData.types would be wrong, and duplicates data would be copied to clipboard target.
Solution: Use ListHashSet data Structure instead of Vector for m_availMimeTypes.

2022-02-10 01:46 UTC, kevinrushforth commented
/reviewers 2

2022-02-24 13:20 UTC, arapte requested changes
The fix itself looks good. Suggested few minor changes.
Regarding test:
Observed that the test does not fail without this fix. Please recheck.
Also, I would recommend to add new tests to test the behavior mentioned in JBS, and modify any pre-existing tests if they now become invalid with fix.

2022-02-24 15:31 UTC, jaybhaskar commented on modules/javafx.web/src/main/native/Source/WebCore/platform/java/PasteboardJava.cpp
> +    data->setData(DataObjectJava::mimeHTML(),jGetPlainText());
done

2022-02-24 15:33 UTC, jaybhaskar commented on modules/javafx.web/src/test/java/test/javafx/scene/web/HTMLEditingTest.java
> +
done

2022-02-24 16:34 UTC, jaybhaskar commented
The commit was before the latest webkit update , yes the test pass without fix, i will investigate and apply the required change

2022-02-25 07:17 UTC, jaybhaskar commented
All , requested changes applied.

2022-02-25 14:50 UTC, kevinrushforth reviewed
The fix looks good to me, but the test still needs additional changes. Then new test should fail without your fix and pass with your fix (as of now it passes either with or without your fix, so it isn't actually testing the fix).

Also, I think you might have misunderstood Ambarish's comment about the test. Rather than modifying the existing `clipboardGetDataOnPaste ` test method, I recommend to leave it alone and add a new test method.

2022-02-25 14:50 UTC, kevinrushforth commented on modules/javafx.web/src/test/java/test/javafx/scene/web/HTMLEditingTest.java
> +                    toString(), clipboardData + defaultText);
The expected and actual values are backwards; the first of the two objects being compared should be the expected value. I see that this is a preexisting bug in the test. I recommend fixing this in the new test (while leaving the existing test method as is).

2022-02-25 14:50 UTC, kevinrushforth commented on modules/javafx.web/src/test/java/test/javafx/scene/web/HTMLEditingTest.java
> +                    "2");
Same comment as above about expected and actual being backwards.

2022-03-04 15:06 UTC, kevinrushforth approved these changes
The new manual test looks good. It fails without the fix and passes with the fix.

2022-03-05 18:20 UTC, arapte approved these changes
looks good to me too.

2022-03-06 03:51 UTC, jaybhaskar commented
/integrate

2022-03-07 08:48 UTC, arapte commented
/sponsor

2022-03-07 08:49 UTC, closed without merging