8290274: DRT 27 tests fail due to xml not well formed error on window
openjdk/jfx pull request #866
Opened 2022-08-10 10:06 UTC by jaybhaskar

Issue: xml not well-formed error occurs at XML document parser.
Issue: doEnd() call not needed for JAVA platform, as it is making XMLDocumentParserLibxml2 xml not well-formed error.

2022-08-10 12:46 UTC, kevinrushforth commented
Can you say why the `doEnd` call is not needed for the Java platform? Have you verified that there is no adverse effect to skipping it?

/reviewers 2

2022-08-11 11:37 UTC, jaybhaskar commented
According to comments mention in the source code:
void XMLDocumentParser::end()
{
    // XMLDocumentParserLibxml2 will do bad things to the document if doEnd() is called.
    // I don't believe XMLDocumentParserQt needs doEnd called in the fragment case.
 
The doEnd() call not needed for JAVA Platform also, as it is affecting libxml2 parser to generate xml not well formed error.

I have tested it , it fixes 27 test cases with no side effects for other drt tests.

2022-08-11 15:44 UTC, kevinrushforth approved these changes
Looks fine then.

2022-08-17 15:26 UTC, kevinrushforth requested changes
Additional testing reveals a test failure on macOS that needs to be evaluated.

2023-05-27 02:40 UTC, closed without merging