9073896: Update ScrollPane.java
openjdk/jfx pull request #887
Opened 2022-08-31 14:19 UTC by douglasheldoracle

Fix two typos in the JavaDoc. The links for the vertical property link to the horizontal property.

It's my first commit, so please comment if I haven't followed the commit protocol per expectations.

Note, I no longer have a handle to the JBS title for record 9073896. The record is not available to me: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=9073896

2022-08-31 14:21 UTC, douglasheldoracle commented
/covered
Although on the OCA screen, I was unable to enter "Oracle Corporation" into the employer field.

2022-08-31 14:46 UTC, kevinrushforth commented
> Note, I no longer have a handle to the JBS title for record 9073896.

That's because it is a temporary, internal ID. Once it is transferred to the JDK project in JBS, it will be assigned a (different) permanent ID. I just did that, so here it is:

https://bugs.openjdk.org/browse/JDK-8293171

You will need to change this PR title to match the bug ID and title of the JBS issue.

> Please allow for a few business days to verify that your employer has signed the OCA.

@robilad will reach out to you regarding this.

2022-08-31 15:12 UTC, douglasheldoracle commented
I received an acknowledgment email from Bug-Report-Daemon_WW@ORACLE.COM and have updated the Pull Request title.

2022-09-01 23:00 UTC, andy-goryachev-oracle approved these changes
thank you for fixing this!

2022-09-02 04:11 UTC, hjohn requested changes
You'll need to update the copyright year on the file you changed:

    Copyright (c) 2010, 2022, Oracle and/or its affiliates. All rights reserved.

2022-09-05 14:11 UTC, kevinrushforth commented
> You'll need to update the copyright year on the file you changed:

That's an optional step, and in general I don't ask that developers do this (although I certainly don't object if they do). We (Ambarish) periodically run a script that bumps all the needed copyrights.

2022-09-05 14:13 UTC, kevinrushforth commented
@douglasheldoracle regardless of whether or not you fix this, please so _not_ create a new pull request. Any update to a PR based on review comments should be done by pushing new commits to your feature branch. I closed PR #890

2022-09-05 15:35 UTC, douglasheldoracle commented
> ### Progress
> * [x]  Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
> * [x]  Change must not contain extraneous whitespace
> * [x]  Commit message must refer to an issue

As the requestor am I responsible for checking the boxes in this first automated comment? (I have checked the final one now)

2022-09-05 15:42 UTC, kevinrushforth commented
> As the requestor am I responsible for checking the boxes in this first automated comment? (I have checked the final one now)

No. As you may notice, the Skara bot has (correctly) unchecked the review box.

> Is my GitHub user account now OCA-verified for future requests?

Yes, verifying your GitHub account is a one-time step good for all subsequent PRs (in any openjdk project).

2022-09-06 13:57 UTC, kevinrushforth commented
@douglasheldoracle The next step is for you to issue the `/integrate` command, whenever you are ready.

2022-09-06 14:04 UTC, douglasheldoracle commented
/integrate

2022-09-06 15:05 UTC, closed without merging