8293883: Add test/.classpath (Eclipse)
openjdk/jfx pull request #901
Opened 2022-09-15 21:55 UTC by andy-goryachev-oracle

Adding a tests/.classpath file to include tests/manual/controls source folder so Eclipse could see/execute manual tests there.

Also, I would rather move the sources there to a specific package (test.manual ?) instead of a default package. Any objections?

2022-09-16 16:49 UTC, kevinrushforth commented
> Also, I would rather move the sources there to a specific package (test.manual ?) instead of a default package. Any objections?

That should probably be done via a separate cleanup bug, since it is outside the scope of this IDE-only fix. It would make sense to at least look at all of the manual tests (since they all exist in the unnamed package), even if you want to limit the scope of the follow-on bug to the manual controls tests.

2022-09-22 19:51 UTC, nlisker commented
I was actually reviewing it just now.

Same as with apps, this is not the way the tests should be ordered. While it allows to run them from Eclipse, the way the tests are currently divided means that they should be (sub-) projects. We will need a follow-up on this.

@kevinrushforth Are you planning on continuing the cleanup of apps and tests soon? If so, we should wait for it with the Eclipse changes.

2022-09-22 19:54 UTC, nlisker requested changes
There are sources under `tests/performance` and `tests/manual` that should also be included in the classpath.

2022-09-22 20:07 UTC, andy-goryachev-oracle commented
> There are sources under `tests/performance` and `tests/manual` that should also be included in the classpath.

I would like to limit the scope of this PR.  

The problem is that one thing leads to another - and the fact that all these manual tests are using the default package instead of their own individual packages might lead to issues and/or require more time and attention.

2022-09-22 20:18 UTC, nlisker commented
The default package is pre-existing bad practice, but doesn't pose an issue, I tried it myself. It makes little sense to add just one source folder while neglecting all the others. If we are editing this classpath to make the tests runnable (even if with the incorrect configuration), then we should make the tests runnable.

2022-09-22 20:29 UTC, andy-goryachev-oracle commented
Added more dirs under manual/ and performance/ - had to skip certain directories that looked like projects in their own right, or that required additional dependencies.

2022-09-23 21:09 UTC, nlisker approved these changes

2022-09-23 21:16 UTC, andy-goryachev-oracle commented
/integrate

2022-09-23 21:20 UTC, nlisker commented
/sponsor

2022-09-23 21:23 UTC, closed without merging